### ISSUE TITLE
Global overrides for buttons

### ISSUE THREAD

**Issue by swati-malhotra** [LaNsHoR/basic-modals#1]
[x] Feature Request

I love using this plugin, but can you please add global overrides for buttons, say if I want to change the title of accept button in prompt then I have to do it on every call, whereas if I could override it globally then that will save us a lot of time.

Regards
Swati Malhotra

**Comment by LaNsHoR** [comment]
Yep, that's a good point. I'll add an option to set some defaults: depending of how busy I am it will take a few days or a few weeks.

Thanks for the feedback!

**Comment by LaNsHoR** [comment]
Hello! This finally has been quicker than I expected and it's implemented now in the version 1.1.0.

**Important**: The previous CSS class `.BasicModalsTitle` has been renamed to `.BasicModalsContent`. If you added some custom CSS rules using that class, please, update your CSS to use `.BasicModalsContent` instead of `.BasicModalsTitle`.

`.BasicModalsTitle` still exists but it is a "new" class which has been added for titles, replacing the old one which is now `.BasicModalsContent`.

**Comment by LaNsHoR** [comment]
BTW: The README has been updated explaining how to use the new features :)

**Comment by swati-malhotra** [comment]
Got it, will try it out and let you know.

Cheers!
Swati
