### ISSUE TITLE
Modal Title

### ISSUE THREAD

**Issue by swati-malhotra** [LaNsHoR/basic-modals#2]
[x] Feature Request

This is my second feature request.
We need an option to add a modal title / header to the popup in order to make it clear to the user what is it for and also to match it with other modals in the product.

Attaching a screenshot.

Current Behavior
![image](https://user-images.githubusercontent.com/69489481/118363166-15f89580-b561-11eb-9bbd-255d712b0e27.png)

Expected Behavior
![image](https://user-images.githubusercontent.com/69489481/118363232-6839b680-b561-11eb-9374-ac6de06d3280.png)

**Comment by LaNsHoR** [comment]
Yep, I planned to add a title option. It probably will be ready in a few days :)

Thanks!

**Comment by LaNsHoR** [comment]
Hello! This finally has been quicker than I expected and it's implemented now in the version 1.1.0.

**Important**: The previous CSS class `.BasicModalsTitle` has been renamed to `.BasicModalsContent`. If you added some custom CSS rules using that class, please, update your CSS to use `.BasicModalsContent` instead of `.BasicModalsTitle`.

`.BasicModalsTitle` still exists but it is a "new" class which has been added for titles, replacing the old one which is now `.BasicModalsContent`.

**Comment by LaNsHoR** [comment]
BTW: The README has been updated explaining how to use the new features :)

**Comment by swati-malhotra** [comment]
Awesome job guys, thank you so much!
