### ISSUE TITLE
Modals not working with Angular 13

### ISSUE THREAD

**Issue by swati-malhotra** [LaNsHoR/basic-modals#4]
[x] Bug

I am using this modal as explained in the Read Me, but when I write code to invoke it I receive the following error on browser console.

![image](https://user-images.githubusercontent.com/69489481/177630070-f253af0d-c9b6-4508-8d9c-3ae2feaf829f.png)

![image](https://user-images.githubusercontent.com/69489481/177629913-25edfe02-c32c-4949-9e29-02514be79db2.png)

If I remove the line "confirm('Are you sure');" the app starts working fine again.

I tried installing both version 0.2.0 and 1.1.0 but no luck.

Any reason?

**Comment by LaNsHoR** [comment]
Thanks for reporting this, looks like a problem with the line 12 in https://github.com/LaNsHoR/html-css-builder/blob/main/index.js

I think I can fix it quickly, instead of ` for(selector in styles)` we can try with ` for(let selector in styles)` and hopefully that will work. As it is should work in vanilla javascript but maybe the transpiler wants a explicit declaration there...

It should have a fix ready in a few minutes.

**Comment by LaNsHoR** [comment]
I just made that change and I bumped the version to 1.1.1.

Please, update to 1.1.1 and confirm if it works, as I can't replicate the problem myself to test the fix.

Thanks!
